import type { Metadata } from "next";
import { Lexend, Sofia_Sans } from "next/font/google";
import "./globals.css";
import AppNavbar from "./Components/common/AppNavbar";
import AppFooter from "./Components/common/AppFooter";

// Load Lexend font
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // customize as you need
});
const sofia = Sofia_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-sofia",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} ${sofia.variable} font-sans`}>
        <AppNavbar />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
