import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import AppNavbar from "./Components/common/AppNavbar";
import AppFooter from "./Components/common/AppFooter";

// Load Lexend font
const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // customize as you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} w-full relative`}>
        <AppNavbar />
        {children}
        {/* <AppFooter /> */}
      </body>
    </html>
  );
}
